plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.10'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.gtech'
version = '0.0.1-SNAPSHOT'
description = 'Ecommerce service'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'com.fasterxml.uuid:java-uuid-generator:5.1.0'
    implementation 'commons-validator:commons-validator:1.9.0' // lib de validacao
    implementation 'io.hypersistence:hypersistence-tsid:2.1.4' // TSID lib
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'com.h2database:h2'
    compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.assertj:assertj-core:3.27.3'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

// roda JUNIT5 por padrão
tasks.named('test') {
	useJUnitPlatform()
}

// classe test não deve rodar testes de integração
test {
    filter {
        excludeTestsMatching("*IT")
    }
}

// check roda ambos testes
tasks.named('check') {
    dependsOn(test, integrationTest)
}

// nova task de test focada em integração
tasks.register('integrationTest', Test) {
    description = 'Run integration tests.'
    group = 'verification'

    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath

    shouldRunAfter test

    useJUnitPlatform()

    testLogging {
        events "passed"
    }

    filter {
        includeTestsMatching "*IT"
        excludeTestsMatching "*Test"
    }
}