plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.10'
	id 'io.spring.dependency-management' version '1.1.7'
    id 'org.springframework.cloud.contract' version '4.3.0'
}

group = 'com.gtech'
version = '0.0.1-SNAPSHOT'
description = 'Ecommerce service'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
    mockitoAgent
}

repositories {
	mavenCentral()
}

ext {
    set('springCloudVersion', "2025.0.0")
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'com.fasterxml.uuid:java-uuid-generator:5.1.0'
    implementation 'org.modelmapper:modelmapper:3.2.4' // mapeador automatico
    implementation 'commons-validator:commons-validator:1.9.0' // lib de validacao
    implementation 'io.hypersistence:hypersistence-tsid:2.1.4' // TSID lib
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    runtimeOnly 'com.h2database:h2'
    compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.cloud:spring-cloud-starter-contract-verifier'
    testImplementation 'org.springframework.cloud:spring-cloud-starter-contract-stub-runner'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.assertj:assertj-core:3.27.3'
    testImplementation 'io.rest-assured:rest-assured'
    testImplementation 'io.rest-assured:spring-mock-mvc'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    mockitoAgent('org.mockito:mockito-core:5.14.2') {transitive = false}
}

contracts {
    packageWithBaseClasses = "com.gtech.algashop.contract.base"
    baseClassMappings {
        baseClassMapping("shoppingcart", "com.gtech.algashop.contract.base.ShoppingCartBase")
        baseClassMapping("order", "com.gtech.algashop.contract.base.OrderBase")
    }
}

//contracts {
//    testFramework ='JUNIT5'
//    testMode = 'MockMvc'
//    contractsDslDir = project.file("${layout.projectDirectory}/src/contractTest/resources/contracts")
//}

// roda testes de contratos
tasks.named('contractTest') {
    useJUnitPlatform()
}

// roda JUNIT5 por padrão
tasks.named('test') {
	useJUnitPlatform()
}

// check roda todos os tipos de testes
tasks.named('check') {
    dependsOn(test, contractTest, integrationTest)
}

// classe test não deve rodar testes de integração
test {
    filter {
        excludeTestsMatching("*IT")
    }
    jvmArgs += "-javaagent:${configurations.mockitoAgent.asPath}"
}

// nova task de test focada em integração
tasks.register('integrationTest', Test) {
    description = 'Run integration tests.'
    group = 'verification'
    jvmArgs += "-javaagent:${configurations.mockitoAgent.asPath}"

    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath

    shouldRunAfter test

    useJUnitPlatform()

    testLogging {
        events "passed"
    }

    filter {
        includeTestsMatching "*IT"
        excludeTestsMatching "*Test"
    }
}